// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emquqlsmchcvmvhtzuff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcXVxbHNtY2hjdm12aHR6dWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzA4ODYsImV4cCI6MjA2MjgwNjg4Nn0.yDZo7x8fLVpGUrp-WCPQi47Tb04mG2DV9biHNp0ycmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);